# Generated by Django 5.2.12 on 2026-03-19 22:18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_th', models.CharField(blank=True, max_length=100)),
                ('description_en', models.TextField(blank=True)),
                ('description_th', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'menu_categories',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Liters'), ('ml', 'Milliliters'), ('unit', 'Units/Pieces')], default='g', max_length=10)),
                ('current_stock_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=200)),
                ('name_th', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_th', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('calories', models.PositiveIntegerField(default=0, help_text='kcal per serving')),
                ('protein_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('fiber_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('sodium_mg', models.PositiveIntegerField(default=0)),
                ('sugar_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('ingredients_list', models.TextField(blank=True, help_text='Full ingredient list')),
                ('allergens', models.JSONField(blank=True, default=list, help_text="['peanuts', 'shellfish', etc.]")),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_dairy_free', models.BooleanField(default=False)),
                ('is_halal', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('spice_level', models.PositiveSmallIntegerField(choices=[(0, 'Not Spicy'), (1, 'Mild'), (2, 'Medium'), (3, 'Hot')], default=0)),
                ('heating_instructions_en', models.TextField(blank=True)),
                ('heating_instructions_th', models.TextField(blank=True)),
                ('storage_instructions', models.TextField(blank=True, default='Keep refrigerated at 4°C or below')),
                ('shelf_life_days', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('rotation_week', models.PositiveSmallIntegerField(default=1, help_text='Menu rotation week (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('available_from_date', models.DateField(blank=True, null=True)),
                ('available_until_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='menu.category')),
            ],
            options={
                'db_table': 'menu_items',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='MenuModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_th', models.CharField(blank=True, max_length=100)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price change (+/-)', max_digits=6)),
                ('calories_delta', models.IntegerField(default=0)),
                ('protein_delta_g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carbs_delta_g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fat_delta_g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='menu.menuitem')),
            ],
            options={
                'db_table': 'menu_modifiers',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='RecipeComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='menu.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_components', to='menu.menuitem')),
            ],
            options={
                'db_table': 'recipe_components',
            },
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_active', 'rotation_week'], name='menu_items_is_acti_fda680_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_active'], name='menu_items_categor_c203aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipecomponent',
            unique_together={('menu_item', 'ingredient')},
        ),
    ]
