# Generated by Django 5.2.12 on 2026-03-19 22:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('postal_code_prefix', models.CharField(db_index=True, max_length=10, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('city', models.CharField(default='Oakville', max_length=100)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('5.99'), max_digits=6)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('75.00'), help_text='Order subtotal for free delivery', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Lower = higher priority')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delivery_zones',
                'ordering': ['priority', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RouteSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('failed_orders', models.PositiveIntegerField(default=0)),
                ('route_started_at', models.DateTimeField(blank=True, null=True)),
                ('route_completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'route_summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('max_orders', models.PositiveIntegerField(default=50)),
                ('current_orders', models.PositiveIntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('cutoff_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zones', models.ManyToManyField(blank=True, related_name='delivery_windows', to='delivery.deliveryzone')),
            ],
            options={
                'db_table': 'delivery_windows',
                'ordering': ['date', 'time_start'],
            },
        ),
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('route_order', models.PositiveSmallIntegerField(default=0, help_text='Order in delivery route (lower = earlier)')),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('driver_notes', models.TextField(blank=True)),
                ('delivery_photo_url', models.URLField(blank=True, max_length=500)),
                ('customer_feedback', models.TextField(blank=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'driver_assignments',
                'ordering': ['route_order'],
            },
        ),
    ]
