# Generated by Django 5.2.12 on 2026-03-19 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverassignment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignment', to='orders.order'),
        ),
        migrations.AddField(
            model_name='routesummary',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='deliverywindow',
            unique_together={('date', 'time_start', 'time_end')},
        ),
        migrations.AddIndex(
            model_name='driverassignment',
            index=models.Index(fields=['driver', 'status'], name='driver_assi_driver__79860c_idx'),
        ),
        migrations.AddIndex(
            model_name='driverassignment',
            index=models.Index(fields=['assigned_at'], name='driver_assi_assigne_d5fbec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routesummary',
            unique_together={('driver', 'date')},
        ),
    ]
