# Generated by Django 5.2.12 on 2026-03-19 22:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('api_version', models.CharField(blank=True, max_length=20)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('related_order_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('related_subscription_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stripe_webhook_events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type', 'status'], name='stripe_webh_event_t_29000b_idx'), models.Index(fields=['received_at'], name='stripe_webh_receive_034668_idx')],
            },
        ),
    ]
