# Generated by Django 5.2.12 on 2026-03-19 22:18

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_delta', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('reason', models.CharField(choices=[('order_earned', 'Points Earned from Order'), ('order_redeemed', 'Points Redeemed for Discount'), ('referral_bonus', 'Referral Bonus'), ('signup_bonus', 'Sign-up Bonus'), ('admin_adjustment', 'Admin Adjustment'), ('refund_deduction', 'Points Deducted (Order Refund)'), ('expiry', 'Points Expired'), ('promotional', 'Promotional Bonus')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'loyalty_points',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referrer_reward_issued', models.BooleanField(default=False)),
                ('referrer_reward_issued_at', models.DateTimeField(blank=True, null=True)),
                ('referrer_points_earned', models.PositiveIntegerField(default=0)),
                ('referred_reward_issued', models.BooleanField(default=False)),
                ('referred_discount_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'referral_history',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('free_delivery', 'Free Delivery')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('max_uses_per_customer', models.PositiveIntegerField(default=1)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on discount amount (for percentage discounts)', max_digits=10, null=True)),
                ('is_first_order_only', models.BooleanField(default=False)),
                ('is_subscription_only', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coupons',
                'indexes': [models.Index(fields=['code', 'is_active'], name='coupons_code_e67bf2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='marketing.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupon_usages',
            },
        ),
    ]
