# Generated by Django 5.2.12 on 2026-03-19 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_usage', to='orders.order'),
        ),
        migrations.AddField(
            model_name='loyaltypoint',
            name='adjusted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltypoint',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyaltypoint',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='referralhistory',
            name='qualifying_order',
            field=models.ForeignKey(blank=True, help_text='First qualifying order from referred user', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='referralhistory',
            name='referred_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_source', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralhistory',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loyaltypoint',
            index=models.Index(fields=['customer', 'created_at'], name='loyalty_poi_custome_c7c302_idx'),
        ),
        migrations.AddIndex(
            model_name='referralhistory',
            index=models.Index(fields=['referrer', 'referrer_reward_issued'], name='referral_hi_referre_1d560f_idx'),
        ),
    ]
